describe('order coffee spec', () => {
  it('successfully order coffee', () => {
    cy.visit('http://localhost:4200/')
    cy.wait(500)
    cy.get('[data-cy="input-name"]').type('dayat')
    cy.wait(500)
    cy.get('[data-cy="input-password"]').type('naruto')
    cy.wait(500)
    cy.get('[data-cy="btn-login"]').click()
    cy.wait(500)
    cy.get(':nth-child(1) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
    cy.wait(500)
    cy.get('.card-body > .h-full > :nth-child(1)').click()
    cy.wait(500)
    cy.get(':nth-child(2) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
    cy.wait(500)
    cy.get('.card-body > .h-full > :nth-child(2)').click()
    cy.wait(500)
    cy.get(':nth-child(3) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
    cy.wait(500)
    cy.get('.card-body > .h-full > :nth-child(3)').click()
    cy.wait(500)
    cy.get(':nth-child(4) > .card-body > [data-cy="btn-add-menu-item-to-cart"]').click()
    cy.wait(500)
    cy.get('.card-body > .h-full > :nth-child(4)').click()
    cy.wait(500)
    cy.get('[data-cy="btn-checkout"]').click()
    cy.wait(500)
    cy.get('[data-cy="btn-logout"]').click()
    cy.wait(500)
  })
})